# data augmentation
dataset:
  common:
    NAME: MSPDataset
    data_root: ...
    num_points: 4096
    variable: False
  train:
    split: train
    split_file: ...
    loop: 5
  val:
    split: val
    split_file: ...
  test:
    split: test
    split_file: ...

feature_keys: x,heights
#feature_keys: x
num_classes: 2
batch_size: 4
val_batch_size: 1

dataloader:
  num_workers: 6

datatransforms:
  train: [ChromaticAutoContrast, PointsToTensor, PointCloudScaling, PointCloudRotation, PointCloudJitter, ChromaticDropGPU]
  val: [PointsToTensor]
  vote: [ChromaticDropGPU]
  kwargs:
    color_drop: 0.2
    gravity_dim: 2
    scale: [0.9, 1.1]
    angle: [0, 0, 1]
    jitter_sigma: 0.005
    jitter_clip: 0.02

# ---------------------------------------------------------------------------- #
# Training cfgs
# ---------------------------------------------------------------------------- #
val_fn: validate
ignore_index: null 
epochs: 200

cls_weighed_loss: False

criterion_args:
  NAME: CrossEntropy
  label_smoothing: 0.2

optimizer:
 NAME: 'adamw'  # performs 1 point better than adam
 weight_decay: 1.0e-4

# lr_scheduler:
sched: cosine
warmup_epochs: 0

min_lr: 1.0e-5 #
lr: 0.001 # LR linear rule.

grad_norm_clip: 10
use_voting: False
# ---------------------------------------------------------------------------- #
# io and misc
# ---------------------------------------------------------------------------- #
log_dir: /mnt/data/program/Log
save_freq: -1 # save epoch every xxx epochs, -1 only save last and best. 
val_freq: 1

wandb:
  project: PointNeXt-S3DIS

data_name: cmf_msp